# Generated by Django 5.2.3 on 2025-06-15 22:49

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_aluno', models.CharField(blank=True, max_length=50, verbose_name='Digite o nome do Aluno')),
                ('phone_number_aluno', models.CharField(max_length=11, verbose_name='Digite o numero do celular (xx)xxxxx-xxxx')),
                ('email_aluno', models.EmailField(max_length=100, verbose_name='Digite o email do aluno')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, verbose_name='Digite o cpf do aluno')),
                ('birthday_aluno', models.DateField()),
                ('class_choice', models.CharField(blank=True, choices=[('1A', '1 ANO A'), ('1B', '1 ANO B'), ('1C', '1 ANO C'), ('2A', '2 ANO A'), ('2B', '2 ANO B'), ('2C', '2 ANO C'), ('3A', '3 ANO A'), ('3B', '3 ANO B'), ('3C', '3 ANO C')], max_length=2)),
                ('month_choice', models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2)),
                ('faltas_aluno', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('professor_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_professor', models.CharField(max_length=50, verbose_name='Digite o nome do professor')),
                ('phone_number_professor', models.CharField(max_length=11, verbose_name='Digite o numero do celular (xx)xxxxx-xxxx')),
                ('email_professor', models.EmailField(max_length=100, verbose_name='Digite o email do professor')),
                ('cpf_professor', models.CharField(max_length=11, unique=True, verbose_name='Digite o cpf do professor')),
                ('birthday_professor', models.DateField()),
                ('matricula_professor', models.CharField(max_length=11, unique=True, verbose_name='Digite sua matricula: ')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Digite o nome do responsavel')),
                ('phone_number', models.CharField(max_length=15, validators=[api.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Digite o email do responsavel')),
                ('adress', models.CharField(max_length=100, verbose_name='Digite o endereço do responsavel')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[api.validators.validar_cpf], verbose_name='Digite o cpf do responsavel')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadePendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('disciplina', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bimestre')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='Responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsavel'),
        ),
    ]
