# Generated by Django 5.2.3 on 2025-06-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='name',
            new_name='nome',
        ),
    ]
