# Generated by Django 5.2.3 on 2025-06-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_responsavel_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='nome',
            new_name='name',
        ),
    ]
