# Generated by Django 5.2.3 on 2025-06-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_nome_responsavel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='birthday',
            new_name='nascimento',
        ),
    ]
