# Generated by Django 5.2.3 on 2025-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_birthday_responsavel_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='nascimento',
            new_name='birthday',
        ),
    ]
