# Generated by Django 5.2.3 on 2025-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nascimento_responsavel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='birthday',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
