# Generated by Django 5.2.3 on 2025-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_responsavel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='birthday_aluno',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='birthday_professor',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
