# Generated by Django 5.2.3 on 2025-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aluno_month_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phone_number_professor',
            field=models.CharField(max_length=13, verbose_name='Digite o numero do celular (xx)xxxxx-xxxx'),
        ),
    ]
