# Generated by Django 5.2.3 on 2025-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_professor_phone_number_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='phone_number_professor',
            field=models.CharField(max_length=11, verbose_name='Digite o numero do celular (xx)xxxxx-xxxx'),
        ),
    ]
