# Generated by Django 5.2.3 on 2025-06-16 19:57

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_aluno_phone_number_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='phone_number_aluno',
            field=models.CharField(max_length=11, validators=[api.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number_professor',
            field=models.CharField(max_length=11, validators=[api.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[api.validators.validar_telefone], verbose_name='Digite o numero do celular(xx)xxxxx-xxxx'),
        ),
    ]
