# Generated by Django 5.2.3 on 2025-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_aluno_phone_number_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadependente',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CN', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Habilitação técnica')], max_length=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CN', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Habilitação técnica')], max_length=4),
        ),
    ]
