# Generated by Django 5.2.3 on 2025-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_atividadependente_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimestre',
            name='numero',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], unique=True),
        ),
    ]
