# Generated by Django 5.2.3 on 2025-06-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_bimestre_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='name_aluno',
            field=models.CharField(max_length=50, verbose_name='Digite o nome do Aluno'),
        ),
    ]
