# Generated by Django 5.2.3 on 2025-06-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_aluno_name_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da advertência')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início da suspensão')),
                ('data_fim', models.DateField(verbose_name='Fim da suspensão')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
    ]
