# Generated by Django 5.2.3 on 2025-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_advertencia_suspensao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Entrega de Trabalho'), ('feriado', 'Feriado'), ('evento', 'Evento')], max_length=10)),
            ],
        ),
    ]
