# Generated by Django 5.2.3 on 2025-06-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_eventocalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_letivo',
            field=models.PositiveIntegerField(default=2025, verbose_name='Ano Letivo'),
        ),
    ]
