# Generated by Django 5.2.3 on 2025-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_advertencia_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensao',
            name='motivo',
            field=models.CharField(choices=[('AGF', 'Agressão física a colegas ou funcionários'), ('AME', 'Ameaças verbais ou físicas'), ('BLG-R', 'Bullying recorrente ou grave'), ('DSP-G', 'Desrespeito grave à autoridade escolar'), ('VDM', 'Vandalismo / dano intencional ao patrimônio'), ('SUB', 'Uso ou posse de substâncias proibidas'), ('REC', 'Reincidência em comportamentos advertidos'), ('IMP', 'Divulgação de conteúdo impróprio'), ('RFT', 'Roubo ou furto na escola'), ('BRG', 'Participação em brigas ou tumultos graves'), ('RSC', 'Comportamento de risco à integridade física'), ('PRG', 'Porte de armas ou objetos perigosos'), ('FAL', 'Falsificação de documentos ou assinaturas'), ('RES', 'Desrespeito extremo em ambiente escolar'), ('SEG', 'Violação grave de normas de segurança')], max_length=255, verbose_name='Motivo, choice'),
        ),
    ]
