# Generated by Django 5.2.3 on 2025-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_suspensao_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertencia',
            name='motivo',
            field=models.CharField(choices=[('FJI', 'Faltas injustificadas'), ('DSP', 'Desrespeito a colegas ou professores'), ('CEL', 'Uso de celular sem autorização'), ('RGR', 'Descumprimento das regras da escola'), ('AGV', 'Agressões verbais'), ('DPM', 'Dano leve ao patrimônio escolar'), ('DOB', 'Desobediência a orientações'), ('IND', 'Atos de indisciplina em sala'), ('UNI', 'Uso inadequado do uniforme'), ('CPM', 'Comportamento impróprio no ambiente escolar'), ('LGF', 'Uso de linguagem ofensiva'), ('FRA', 'Cola ou fraude em avaliações'), ('BLG', 'Bullying ou assédio'), ('OUTROS', 'Outros motivos')], max_length=255, verbose_name='Motivo'),
        ),
    ]
