# Generated by Django 5.2.3 on 2025-06-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_advertencia_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertencia',
            name='motivo',
            field=models.CharField(choices=[('FJI', '-Faltas injustificadas'), ('DSP', '-Desrespeito a colegas ou professores'), ('CEL', '-Uso de celular sem autorização'), ('RGR', '-Descumprimento das regras da escola'), ('AGV', '-Agressões verbais'), ('DPM', '-Dano leve ao patrimônio escolar'), ('DOB', '-Desobediência a orientações'), ('IND', '-Atos de indisciplina em sala'), ('UNI', '-Uso inadequado do uniforme'), ('CPM', '-Comportamento impróprio no ambiente escolar'), ('LGF', '-Uso de linguagem ofensiva'), ('FRA', '-Cola ou fraude em avaliações'), ('BLG', '-Bullying ou assédio'), ('OUTROS', '-Outros motivos')], max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='suspensao',
            name='motivo',
            field=models.CharField(choices=[('AGF', '-Agressão física a colegas ou funcionários'), ('AME', '-Ameaças verbais ou físicas'), ('BLG-R', '-Bullying recorrente ou grave'), ('DSP-G', '-Desrespeito grave à autoridade escolar'), ('VDM', '-Vandalismo / dano intencional ao patrimônio'), ('SUB', '-Uso ou posse de substâncias proibidas'), ('REC', '-Reincidência em comportamentos advertidos'), ('IMP', '-Divulgação de conteúdo impróprio'), ('RFT', '-Roubo ou furto na escola'), ('BRG', '-Participação em brigas ou tumultos graves'), ('RSC', '-Comportamento de risco à integridade física'), ('PRG', '-Porte de armas ou objetos perigosos'), ('FAL', '-Falsificação de documentos ou assinaturas'), ('RES', '-Desrespeito extremo em ambiente escolar'), ('SEG', '-Violação grave de normas de segurança')], max_length=255, verbose_name='Motivo'),
        ),
    ]
