# Generated by Django 5.2.3 on 2025-06-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_advertencia_motivo_alter_suspensao_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
    ]
