# Generated by Django 5.2.3 on 2025-06-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_responsavel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertencia',
            options={'verbose_name': 'Advertência', 'verbose_name_plural': 'Advertências'},
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='atividadependente',
            options={'verbose_name': 'Atividade pendente ou não entregue', 'verbose_name_plural': 'Atividades pendentes ou não entregues'},
        ),
        migrations.AlterModelOptions(
            name='bimestre',
            options={'verbose_name': 'Bimestre', 'verbose_name_plural': 'Bimestres'},
        ),
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'verbose_name': 'evento do calendário', 'verbose_name_plural': 'eventos do calendário'},
        ),
        migrations.AlterModelOptions(
            name='eventoextracurricular',
            options={'verbose_name': 'Evento extracurricular', 'verbose_name_plural': 'Eventos extracurriculares'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='pagamentopendente',
            options={'verbose_name': 'Pagamento pendente', 'verbose_name_plural': 'Pagamentos pendentes'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='suspensao',
            options={'verbose_name': 'Suspensão', 'verbose_name_plural': 'Suspensões'},
        ),
    ]
