# Generated by Django 5.2.3 on 2025-06-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_advertencia_options_alter_aluno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'verbose_name': 'Evento do calendário', 'verbose_name_plural': 'Eventos do calendário'},
        ),
    ]
