# Generated by Django 5.2.5 on 2025-08-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_eventocalendario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='pagamentopendente',
            options={'verbose_name': 'Pagamento pendente e Mensalidade em Aberto', 'verbose_name_plural': 'Pagamentos pendentes e Mensalidades em Abertos'},
        ),
        migrations.AlterField(
            model_name='atividadependente',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Habilitação técnica')], max_length=4),
        ),
        migrations.AlterField(
            model_name='nota',
            name='disciplina',
            field=models.CharField(choices=[('LING', 'Linguagens'), ('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('DS', 'Habilitação técnica')], max_length=4),
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('computador', 'Computador')], default='livro', max_length=20)),
                ('computador', models.CharField(blank=True, help_text='Identificação do computador', max_length=100, null=True)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.livro')),
            ],
        ),
    ]
