# Generated by Django 5.2.5 on 2025-08-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_livro_alter_pagamentopendente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimolivro',
            options={'verbose_name': 'Empréstimo de Livro ou Computador', 'verbose_name_plural': 'Empréstimos de Livros ou Computadores'},
        ),
    ]
